# Generated by Django 3.2.15 on 2023-06-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230608_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payment', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField(default=0)),
                ('comment', models.TextField()),
                ('payment_photo', models.ImageField(null=True, upload_to='payment/')),
            ],
        ),
    ]
