# Generated by Django 3.2.15 on 2023-07-03 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_confirmpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='delivery',
            field=models.CharField(blank=True, choices=[('ຮຸ່ງອາລຸນ', 'ຮຸ່ງອາລຸນ'), ('ອານຸສິດ', 'ອານຸສິດ')], default='ຮຸ່ງອາລຸນ', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='tel',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
